### PR TITLE
fix: correct & optimize database stamping and migrations in docker setup

### LINKED ISSUE #983: docker: `create_tables` conflicts with database migrations in case of new tables
## Summary 
Right now the docker entrypoint creates a database including all tables, stamps it and migrates the schema if required.

During development and testing I noticed that this flow causes potential problems in case of a new table. 

## Reproduce

- Fire up docker setup, wait for database created and migrated
- Create a new database model and the according migration script
- Depending on your setup rebuild the container 
- Startup the docker setup again
  - In case of an existing database the `create_tables` call will already create the new table but won't stamp the database
  - The according checks will notice the missing stamp and attempt to migrate the database to the new revision what will fail since the table was created before

### PR DESCRIPTION
**Pull request by fritterhoff**
As described in #983 from my point of view the current docker entrypoint has a little painpoint.

This PR adds a new cli command to wait for the database (yeah ... I use `select 1`) and revises the flow a bit.

In the new version the following outputs will be generated:

## First Run

```
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | The file '/etc/edumfa/enckey' already exists.
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | The file '/etc/edumfa/private.pem' already exists.
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | Failed to connect to database. Attempt 1 of 5. Waiting 5 seconds...
edumfa-1  | Failed to connect to database. Attempt 2 of 5. Waiting 5 seconds...
edumfa-1  | Database connection successful.
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
edumfa-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
edumfa-1  | No existing database stamp found.
edumfa-1  | Initializing database and creating tables.
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | <SQLAlchemy mysql+pymysql://edumfa:***@mariadb/edumfa?charset=utf8mb4>
edumfa-1  | Running online
edumfa-1  | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
edumfa-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
edumfa-1  | INFO  [alembic.runtime.migration] Running stamp_revision  -> 2a74c6522937
edumfa-1  | Upgrading Database
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
edumfa-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
edumfa-1  | ++ Upgrading DB schema.
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | Running online
edumfa-1  | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
edumfa-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
edumfa-1  | Creating Admin
```

## Additional run without migration

```
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | The file '/etc/edumfa/enckey' already exists.
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | The file '/etc/edumfa/private.pem' already exists.
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | Database connection successful.
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
edumfa-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
edumfa-1  | Existing database stamp found: 2a74c6522937 (head). Skipping database/table creation.
edumfa-1  | Upgrading Database
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
edumfa-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
edumfa-1  | ++ Upgrading DB schema.
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | Running online
edumfa-1  | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
edumfa-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
edumfa-1  | Creating Admin
```

## Additional run with migration

```
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | The file '/etc/edumfa/enckey' already exists.
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | The file '/etc/edumfa/private.pem' already exists.
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | Database connection successful.
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
edumfa-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
edumfa-1  | Existing database stamp found: 2a74c6522937. Skipping database/table creation.
edumfa-1  | Upgrading Database
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
edumfa-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
edumfa-1  | ++ Upgrading DB schema.
edumfa-1  | Can not import grpc modules - No module named 'google.protobuf'
edumfa-1  | Running online
edumfa-1  | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
edumfa-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
edumfa-1  | INFO  [alembic.runtime.migration] Running upgrade 2a74c6522937 -> 2bed9a05c8d7, empty message
edumfa-1  | Creating Admin
```

### CODE REVIEW

File: deploy/docker/entrypoint.sh [hunk 1]
```diff
@@ -20,26 +20,22 @@ edumfa-manage -q create_enckey || true
...
-done
+# Wait for DB to be available
+edumfa-manage -q wait_for_db || exit 1
 
-# Check and stamp DB
-STAMP=$(edumfa-manage -q db current -d /usr/local/lib/edumfa/migrations)
-if [[ -z "${STAMP//Running online/}" ]]; then
-  edumfa-manage -q db stamp head -d /usr/local/lib/edumfa/migrations
+# Check for an existing stamp -> if none exists, we have to create tables first
+# Create tables will create new tables even if there is already a database -> might break migrations that try to do this actions on their own!
```
Comment (aleyna72072) [inline deploy/docker/entrypoint.sh]:
```suggestion
# create_tables will create new tables even if there is already a database -> might break migrations that try to do these actions on their own!
```
Not sure what you mean with "might break migrations that try to do these actions on their own" though.

File: edumfa/commands/manage/core.py [hunk 2]
```diff
@@ -221,6 +221,49 @@ def create_tables(stamp=False):
...
+)
+@click.option(
+    "-s",
+    "--sleep",
+    type=int,
+    default=3,
+    show_default=True,
+    help="Time to sleep in seconds between the attempts to wait for the database to become available.",
+)
+def wait_for_db(attempts, sleep):
```
Comment (aleyna72072) [inline edumfa/commands/manage/core.py]:
```suggestion
def wait_for_db(attempts: int, sleep: int) -> None:
```

**Review by aleyna72072 — APPROVED** [review]
Nice, the wait_for_db-command is really handy.  
I'd love to at some point get rid of the `edumfa-manage -q db current` parsing. Do you think we could just add a check in `create_tables` if there is one row in `alembic_version.version_num`?

File: deploy/docker/entrypoint.sh (hunk 1 above)
Comment (fritterhoff) [reply deploy/docker/entrypoint.sh]: As explained in the PR this will always create missing tables. In case of a migration that does not handle an existing table the migration will simply throw an exception.

**Comment by fritterhoff** [comment]
> Nice, the wait_for_db-command is really handy. I'd love to at some point get rid of the `edumfa-manage -q db current` parsing. Do you think we could just add a check in `create_tables` if there is one row in `alembic_version.version_num`?

Mhm. We could simply remove the `Running online` since this is generated by us... 
https://github.com/eduMFA/eduMFA/blob/0fd65e0e0bf7a554ea376dc94415219ad358afd6/migrations/env.py#L106-L111

Then it only should generate the version or an empty output?

**Comment by aleyna72072** [comment]
> Mhm. We could simply remove the `Running online` since this is generated by us...

Or print it to STDERR instead?

**Comment by aleyna72072** [comment]
@fritterhoff  What do you think? This removes the need for the user to ever mess with the DB stamp. A DB without a stamp is not something we should support imo.

File: edumfa/commands/manage/core.py [hunk 3]
```diff
@@ -215,12 +217,64 @@ def create_tables(stamp=False):
...
+    """
+    Wait until the database is available.
+
+    :param attempts: Amount of tries to connect.
+    :param sleep: Time to sleep in seconds between connection attempts.
+    """
+    import time
+
+    from sqlalchemy import text
+    from sqlalchemy.exc import OperationalError
```
Comment (aleyna72072) [inline edumfa/commands/manage/core.py:258]: Is it considered good practice to have imports inside the code? Actually no idea.

**Comment by aleyna72072** [comment]
- [x] Use Table object instead
- [x] Remove more references to stamping (Ubuntu package?)

File: edumfa/commands/manage/core.py (hunk 3 above)
Comment (aleyna72072) [reply edumfa/commands/manage/core.py:258]: @Luc1412 Do you know something about this? Not that it's important, but in spirit of good code 🙂 .

**Comment by aleyna72072** [comment]
@fritterhoff changed the SQL statement to use SQLAlchemy, it's a little more verbose now. Tested the Ubuntu packages, all seems well.

EDIT: forgot to push :smile:
